server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/springboot_jpa_demo_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: springboot_jpa_demo_dba
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      async-init: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  data:
    redis:
      repositories:
        enabled: false
    web:
      pageable:
        default-page-size: 20
        max-page-size: 500
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

redis:
  database: 0
  host: localhost
  port: 36379
  password: 123456
  timeout: 0
  pool:
    max-idle: 8
    min-idle: 0
    max-active: 8
    max-wait: -1
#  cluster:
#    nodes:
#      - 127.0.0.1:7001
#      - 127.0.0.1:7002
#      - 127.0.0.1:7003
#      - 127.0.0.1:7004
#      - 127.0.0.1:7005
#      - 127.0.0.1:7006


flake:
  epoch: 1480550400000
  datacenter: 1
  worker: 1

session:
  # 有效期 秒
  expiry-time: 7200

oss:
  # OSS文件存储仓库 目录
  repo: ./oss-repo

swagger:
  # true:启用swagger false关闭 线上系统需要关闭
  enabled: true

# 自定义Mapper 模仿Mybatis的Mapper 增强Spring Data JPA对于复杂SQL的处理
mapper:
  base-packages: com.springboot.jpa.demo
